config/routes.rb
Beeronrails::Application.routes.draw do
  get "about/index"

  get "about", to: "about#index"
  
  get "beer/index"
  get "beer/denied"

  get "breweries/autocomplete"
  get "breweries/polish"
  get "breweries/foreign"
  get "breweries/search"
  get "breweries/search/:term", to: "breweries#search"

  get "beers/polish"
  get "beers/foreign"
  get "beers/new"
  get "beers/search"
  get "beers/search/:term", to: "beers#search"

  resources :beers
  resources :breweries

  root :to => "beers#index"

  match '*unmatched_route', :to => 'application#raise_not_found!'

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
	attr_accessible :nazwa

	validates :nazwa, presence: true

	def country
		beer = Beer.find(:first, :conditions => [ "brewery_id = ?", self.id ])

		unless beer.nil?
			return beer.country
		else
			return "_"
		end
	end

	def beer_count
		return Beer.find(:all, :conditions => ["brewery_id = ?", self.id]).count
	end

	def permalink
    	return self.nazwa.parameterize
  	end

  	def to_param
    	"#{id}-#{permalink}"
  	end
end

app/controllers/breweries_controller.rb
require "ffi-icu"

class BreweriesController < ApplicationController
  before_filter :authenticate, :except => [:index, :show, :polish, :foreign, :search]
  def index
  	@breweries = Brewery.all

    collator = ICU::Collation::Collator.new("pl_PL")

    @breweries.sort! { |a, b| collator.compare(a.nazwa, b.nazwa) }

    @breweries = Kaminari.paginate_array(@breweries).page(params[:page]).per(25)
  end

  def polish
    brew = Brewery.all

    collator = ICU::Collation::Collator.new("pl_PL")

    brew.sort! { |a, b| collator.compare(a.nazwa, b.nazwa) }

    brew_temp = Array.new

    brew.each { |brewery| 
     
      if brewery.country == "pl"
        brew_temp.push(brewery)
      end
    }

    @breweries = Kaminari.paginate_array(brew_temp).page(params[:page]).per(25)
  end

  def foreign
    brew = Brewery.all

    collator = ICU::Collation::Collator.new("pl_PL")

    brew.sort! { |a, b| collator.compare(a.nazwa, b.nazwa) }

    brew_temp = Array.new

    brew.each { |brewery| 
     
      unless brewery.country == "pl"
        brew_temp.push(brewery)
      end
    }

    @breweries = Kaminari.paginate_array(brew_temp).page(params[:page]).per(25)
  end

   def search
    unless params[:term].nil?
      @breweries = Brewery.where("nazwa LIKE ?", "%"+params[:term]+"%")

      collator = ICU::Collation::Collator.new("pl_PL")

      @breweries.sort! { |a, b| collator.compare(a.nazwa, b.nazwa) }

      @breweries = Kaminari.paginate_array(@breweries).page(params[:page]).per(25)
    end
  end
    
  def show
  	@brewery = Brewery.find(params[:id])
  	@beers = Beer.find(:all, :conditions => "brewery_id = " + @brewery.id.to_s)
  end

  def edit
      @brewery = Brewery.find(params[:id])
  end

  def update
    @brewery = Brewery.find(params[:id])

    if @brewery.update_attributes(params[:brewery])
      redirect_to @brewery
    else
      render 'edit'
    end
  end

  def destroy
    @brewery = Brewery.find(params[:id])
    @brewery.destroy
 
    redirect_to breweries_path
  end

  def autocomplete
    @brewer = Brewery.where("nazwa LIKE ?", "%"+params[:term]+"%")

    resp = Array.new

    @brewer.each { |brewery|
      resp.push ({ "id" => brewery.id, "label" => brewery.nazwa, "value" => brewery.nazwa})
    }

    render json: resp
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_list.html.erb
<div class="pull-right">
<%= paginate @breweries %>
</div>

<table class="table table-striped">
  <tr>
    <th>Brewery name</th>
    <th>Beer count</th>
    <th>Country</th>
  </tr>
 
  <% @breweries.each do |brewery| %>
    <tr>
      <td><%= link_to brewery.nazwa, brewery_path(brewery) %></td>
      <td><%= brewery.beer_count %></td>
      <td><img src="/assets/flags/<%= brewery.country %>.png"/></td>
    </tr>
  <% end %>
</table>

<div class="pull-right">
<%= paginate @breweries %>
</div>

app/views/breweries/_searchlist.html.erb
<%= paginate @breweries %>

<table class="table table-striped">
  <tr>
    <th>Brewery name</th>
    <th>Beer count</th>
    <th>Country</th>
  </tr>
 
  <% @breweries.each do |brewery| %>
    <tr>
      <td><%= link_to raw(brewery.nazwa.sub params[:term], "<strong>" + params[:term] + "</strong>"), brewery_path(brewery) %></td>
      <td><%= brewery.beer_count %></td>
      <td><img src="/assets/flags/<%= brewery.country %>.png"/></td>
    </tr>
  <% end %>
</table>

<%= paginate @breweries %>

app/views/breweries/edit.html.erb
<% if @brewery.errors.any? %>
    <% @brewery.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

<div class="page-header">
	<h1>Editing <em><%= @brewery.nazwa %></em> <br/> <small><%= link_to 'or go back', breweries_path %></small></h1>
</div>

<div style="max-width: 600px; margin: 0 auto">

<%= form_for @brewery do |f| %>
	<div class="form-group">
	<%= f.text_field :nazwa, :class => "form-control", :autofocus => '', :placeholder => "Brewery name" %>
	</div>

	<div class="form-group">
    <%= f.submit 'Save', :class => "form-control btn btn-primary" %>
  	</div>
<% end %>
</div>

app/views/breweries/foreign.html.erb
<div class="page-header">
  <h1>Breweries</h1>
</div>

<ul class="nav nav-tabs nav-justified" role="tablist">
	<li><%= link_to "All", breweries_path %></li>
	<li><%= link_to "Polish", breweries_polish_path %></li>
	<li class="active"><%= link_to "Foreign", breweries_foreign_path %></li>
</ul>

<%= render 'list' %>

app/views/breweries/index.html.erb
<div class="page-header">
  <h1>Breweries</h1>
</div>

<ul class="nav nav-tabs nav-justified" role="tablist">
	<li class="active"><%= link_to "All", breweries_path %></li>
	<li><%= link_to "Polish", breweries_polish_path %></li>
	<li><%= link_to "Foreign", breweries_foreign_path %></li>
</ul>

<%= render 'list' %>

app/views/breweries/polish.html.erb
<div class="page-header">
  <h1>Breweries</h1>
</div>

<ul class="nav nav-tabs nav-justified" role="tablist">
	<li><%= link_to "All", breweries_path %></li>
	<li class="active"><%= link_to "Polish", breweries_polish_path %></li>
	<li><%= link_to "Foreign", breweries_foreign_path %></li>
</ul>

<%= render 'list' %>

app/views/breweries/search.html.erb
<h1>Search<% if params[:term] %><% unless params[:term].empty? %>ing for "<em><%= params[:term] %></em>"
		 <small style="font-size: 40%"> get a <a href="/beers/search/<%= params[:term] %>">permalink</a> to this search</small>
		 <%end%></h1>
		<%end%>
</div>


<div style="max-width: 600px; margin: 0 auto">
	<%= form_tag breweries_search_path, :method => 'get' do %>
	<div class="form-group">
		<div class="input-group">
			<%= text_field_tag :term, params[:term], :class => "form-control input-lg", :placeholder => "Brewery name..."%>
				<div class="input-group-addon">
					<%= submit_tag "Search", :name => nil, :class => "btn btn-success", :style => "height: 32px" %>
				</div>
		</div>
	</div>
	<%end%>
</div>

<% if params[:term] %>
<% unless params[:term].empty? %>

<%= render 'searchlist' %>

<%end%>
<%end%>

app/views/breweries/show.html.erb
<div class="page-header">
  <h1><%= @brewery.nazwa %> <span class="label label-default"><%= @beers.count %></span> 
  <% unless @beers.first.country == "_" %>
  <br/><small>A brewery in <%= IsoCountryCodes.find(@beers.first.country).name %> <img style="vertical-align: baseline" src="/assets/flags/<%= @beers.first.country %>.png" /></small>
  <% end %>
  </h1>


  <h3 class="pull-right">
    <%= link_to "Edit", edit_brewery_path(@brewery), :class => "btn btn-primary" %>
    <% if @beers.count < 1 %>
    <%= link_to 'Delete', brewery_path(@brewery),
                    method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
    <% else %>
    <%= link_to 'Delete', "#", :onclick => 'alert("Can\'t remove a brewery that still has beers.");', :class => "btn btn-danger" %>
    <% end %>
  </h3>
</div>

<h2>Beers from this brewery:</h2><br/>

<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>Beer name</th>
  </tr>

  <% @beers.each do |beer| %>
    <tr>
      <td><%= beer.id %></td>
      <td><%= link_to beer.nazwa, beer_path(beer) %></td>
    </tr>
  <% end %>
</table>
</table>