config/routes.rb
Beeronrails::Application.routes.draw do
  get "about/index"

  get "about", to: "about#index"
  
  get "beer/index"
  get "beer/denied"

  get "breweries/autocomplete"
  get "breweries/polish"
  get "breweries/foreign"
  get "breweries/search"
  get "breweries/search/:term", to: "breweries#search"

  get "beers/polish"
  get "beers/foreign"
  get "beers/new"
  get "beers/search"
  get "beers/search/:term", to: "beers#search"

  resources :beers
  resources :breweries

  root :to => "beers#index"

  match '*unmatched_route', :to => 'application#raise_not_found!'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  attr_accessor :icons
  attr_accessible :foto, :komentarz, :kraj, :nazwa, :brewery_id, :barcode, :icons, :local_image

  mount_uploader :local_image, LocalImageUploader

  validates :nazwa, presence: true
  validates :kraj, presence: true

  attr_accessor :inner_brewery

  def brewery_name
    if self.brewery_id.nil?
      return ""
    end

  	if @inner_brewery
  		return @inner_brewery
  	else 
  		@inner_brewery = Brewery.find(self.brewery_id).nazwa
  		return @inner_brewery
  	end
  end

  def country
    if self.kraj.nil?
      return "_"
    end

    unless self.kraj == "_"
      return self.kraj
    else
      country = EanCountry.infer(self.barcode)
      unless country.nil?
        return country.downcase
      else
        return "_"
      end
    end
  end

  def permalink
    return self.nazwa.parameterize
  end

  def to_param
    "#{id}-#{permalink}"
  end
end

app/controllers/beer_controller.rb
class BeerController < ApplicationController
  before_filter :authenticate, :except => [:index, :denied]

  def index
  end
end

app/controllers/beers_controller.rb
require "ffi-icu"

class BeersController < ApplicationController
	before_filter :authenticate, :except => [:index, :show, :polish, :foreign, :search]

	def new
		@beer = Beer.new
	end

	def create
  		@beer = Beer.new(beer_params)
 
		if @beer.save
			@new_beer = @beer
      @beer = Beer.new
      render 'new'
		else
			render 'new'
		end
	end

	def show
  		@beer = beer_name_add_icons(Beer.find(params[:id]))
	end

	def index
    @all_beers_count = all_beers_count
    @polish_beers_count = polish_beers_count
    @foreign_beers_count = foreign_beers_count

    unless params[:shown]
		  @beers = Beer.all
    else
      if params[:shown] == "bottles"
        @beers = Beer.where("komentarz LIKE ? OR komentarz LIKE ?", "%#butelka%", "%#bottle%")
      elsif
        @beers = Beer.where("komentarz NOT LIKE ? AND komentarz NOT LIKE ?", "%#butelka%", "%#bottle%")
      else
        @beers = Beer.all
      end
    end

		collator = ICU::Collation::Collator.new("pl_PL")

		@beers = @beers.sort! do |a, b| 
			comp = collator.compare(a.brewery_name, b.brewery_name)
			comp = comp.zero? ? collator.compare(a.nazwa, b.nazwa) : comp
      comp.zero? ? a.id <=> b.id : comp
		end

    @beers.each do |beer|
      beer = beer_name_add_icons(beer)
    end

		@beers = Kaminari.paginate_array(@beers).page(params[:page]).per(25)
	end

  def search
    unless params[:term].nil?
      if params[:term].include? "country:"
        country = params[:term].gsub("country:", "")
        brew_temp = Beer.all
        @beers = Array.new

        puts "beers search"
        puts country

        brew_temp.each do |beer|
          if beer.country.to_s.include? country
            @beers.push(beer)
          end
        end
      else
        @beers = Beer.where("nazwa LIKE ? OR barcode LIKE ? OR komentarz LIKE ?", "%"+params[:term]+"%", "%"+params[:term]+"%",  "%"+params[:term]+"%")
      end

      collator = ICU::Collation::Collator.new("pl_PL")

      @beers.sort! do |a, b| 
        comp = collator.compare(a.brewery_name, b.brewery_name)
        comp = comp.zero? ? collator.compare(a.nazwa, b.nazwa) : comp
        comp.zero? ? a.id <=> b.id : comp
      end

      @beers.each do |beer|
        beer = beer_name_add_icons(beer)
      end

      @beers = Kaminari.paginate_array(@beers).page(params[:page]).per(25)
    end
  end

	def edit
		@beer = Beer.find(params[:id])
	end

	def update
		@beer = Beer.find(params[:id])

		if @beer.update_attributes(beer_params)
			redirect_to @beer
		else
			render 'edit'
		end
	end

	def destroy
  		@beer = Beer.find(params[:id])
  		@beer.destroy
 
  		redirect_to beers_path
	end

	def polish
    @all_beers_count = all_beers_count
    @polish_beers_count = polish_beers_count
    @foreign_beers_count = foreign_beers_count

		unless params[:shown]
      @beers = Beer.where(kraj: 'pl')
    else
      if params[:shown] == "bottles"
        @beers = Beer.where("(komentarz LIKE ? OR komentarz LIKE ?) AND kraj LIKE ?", "%#butelka%", "%#bottle%", "pl")
      elsif
        @beers = Beer.where("komentarz NOT LIKE ? AND komentarz NOT LIKE ? AND kraj LIKE ?", "%#butelka%", "%#bottle%", "pl")
      else
        @beers = Beer.all
      end
    end

    collator = ICU::Collation::Collator.new("pl_PL")

    @beers = @beers.sort! do |a, b| 
      comp = collator.compare(a.brewery_name, b.brewery_name)
      comp = comp.zero? ? collator.compare(a.nazwa, b.nazwa) : comp
      comp.zero? ? a.id <=> b.id : comp
    end

    @beers.each do |beer|
      beer = beer_name_add_icons(beer)
    end

    @beers = Kaminari.paginate_array(@beers).page(params[:page]).per(25)
 	end

	def foreign
    @all_beers_count = all_beers_count
    @polish_beers_count = polish_beers_count
    @foreign_beers_count = foreign_beers_count

  	unless params[:shown]
      @beers = Beer.where("kraj != ?", "pl")
    else
      if params[:shown] == "bottles"
        @beers = Beer.where("(komentarz LIKE ? OR komentarz LIKE ?) AND kraj NOT LIKE ?", "%#butelka%", "%#bottle%", "pl")
      elsif
        @beers = Beer.where("komentarz NOT LIKE ? AND komentarz NOT LIKE ? AND kraj NOT LIKE ?", "%#butelka%", "%#bottle%", "pl")
      else
        @beers = Beer.all
      end
    end

    collator = ICU::Collation::Collator.new("pl_PL")

    @beers = @beers.sort! do |a, b| 
      comp = collator.compare(a.brewery_name, b.brewery_name)
      comp = comp.zero? ? collator.compare(a.nazwa, b.nazwa) : comp
      comp.zero? ? a.id <=> b.id : comp
    end

    @beers.each do |beer|
      beer = beer_name_add_icons(beer)
    end

    @beers = Kaminari.paginate_array(@beers).page(params[:page]).per(25)
	end

	private
  		def beer_params
  			# get brewery name
  			brewery_name = params[:beer][:brewery_name].strip

		        @new_brewery = ""

  			@brewery = Brewery.where("nazwa = ?", brewery_name).first

  			if @brewery
  				params[:beer][:brewery_id] = @brewery.id
  			else
  				@brewery = Brewery.new()
  				@brewery.nazwa = brewery_name
  				@brewery.save
			          @new_brewery = brewery_name
  				params[:beer][:brewery_id] = @brewery.id
  			end

    		params.require(:beer).permit(:nazwa, :komentarz, :barcode, :brewery_id, :kraj, :foto, :local_image)
  		end

      def beer_name_add_icons(beer)
        beer.icons = ""
        unless beer.komentarz.empty?
          escaped_comment = beer.komentarz.gsub("'", %q(\\\'))
          beer.icons += "<img src='/assets/icons/comment.png' title='Comment: #{escaped_comment}' />"
        end

        if beer.komentarz.include? "#butelka" or beer.komentarz.include? "#bottle"
          beer.icons += " <img src='/assets/icons/bottle.png' title='This beer is stored as a physical bottle' />"
        end

        if beer.komentarz.include? "#edycjalimitowana" or beer.komentarz.include? "#limited"
          beer.icons += " <img src='/assets/icons/award_star_gold_2.png' title='This beer is a limited edition or an otherwise seasonal product' />"
        end

        if not beer.local_image.url.nil? or beer.foto.length > 1
          beer.icons += " <img src='/assets/icons/camera.png' title='This beer has a photo' />"
        end
        
        return beer
      end

      def all_beers_count
        return Beer.all.count
      end

      def polish_beers_count
        return Beer.where(kraj: 'pl').count
      end

      def foreign_beers_count
        return Beer.where("kraj != ?", "pl").count
      end
end

app/helpers/beer_helper.rb
module BeerHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<div style="max-width: 600px; margin: 0 auto">

<%= form_for @beer, :html => {:multipart => true}  do |f| %>
	<div class="form-group">
	<%= f.text_field :nazwa, :class => "form-control", :autofocus => '', :placeholder => "Beer name" %>
	</div>

	<div class="form-group">
	<%= f.text_field :brewery_name, :class => "form-control", :placeholder => "Brewery", :id => "browar" %>
	</div>

	<div class="form-group">
	<%= f.text_field :kraj, :class => "form-control", :placeholder => "Country of origin (ISO code)" %>
	</div>

	<div class="form-group">
	<%= f.file_field :local_image %>
	</div>

	<div class="form-group">
	<%= f.text_field :foto, :class => "form-control", :placeholder => "or provide photo URL" %>
	</div>

	<div class="form-group">
	<%= f.text_area :komentarz, :class => "form-control", :rows => 3, :placeholder => 'Comment...' %>
	</div>

	<div class="form-group">
	<%= f.text_field :barcode, :class => "form-control", :placeholder => "Barcode"%>
	</div>

	<div class="form-group">
    <%= f.submit 'Save changes', :class => "form-control btn btn-primary" %>
  	</div>
<% end %>
</div>

app/views/beers/_list.html.erb
<% if @beers %>
<div class="pull-right">
<%= paginate @beers %>
</div>
<%end%>

<table class="table table-striped">
  <tr>
    <th>Beer ID</th>
    <th>Beer name</th>
    <th></th>
    <th>Brewery</th>
    <th>Country</th>
  </tr>
 
  <% if @beers %>
  <% @beers.each do |beer| %>
    <tr>
      <td class="beer-id"><%= beer.id %></td>
      <td><%= link_to beer.nazwa, beer_path(beer) %></td>
      <td><%= raw(beer.icons) %></td>
      <td><%= link_to beer.brewery_name, brewery_path(Brewery.find(beer.brewery_id)) %></td>
      <td><a href="/beers/search/country:<%= beer.country %>"><img src="/assets/flags/<%= beer.country %>.png" <% unless beer.country == "_" %>title="<%= IsoCountryCodes.find(beer.country).name %>"<% end %> /></a></td>
    </tr>
  <% end %>
  <%end%>
</table>

<% if @beers %>
<div class="pull-right">
<%= paginate @beers %>
</div>
<%end%>

app/views/beers/_searchlist.html.erb
<% if @beers %>
<%= paginate @beers %>
<%end%>

<table class="table table-striped">
  <tr>
    <th>Beer ID</th>
    <th>Beer name</th>
    <th>Brewery</th>
    <th>Country</th>
    <th>Barcode</th>
  </tr>
 
  <% if @beers %>
  <% @beers.each do |beer| %>
    <tr>
      <td><%= beer.id %></td>
      <td><%= link_to raw( beer.nazwa.sub params[:term], "<strong>"+params[:term]+"</strong>") , beer_path(beer) %> <%= raw(beer.icons) %></td>
      <td><%= link_to beer.brewery_name, brewery_path(Brewery.find(beer.brewery_id)) %></td>
      <td><img src="/assets/flags/<%= beer.country %>.png" /></td>
      <td><%= raw(beer.barcode.sub params[:term], "<strong>"+params[:term]+"</strong>") %></td>
    </tr>
  <% end %>
  <%end%>
</table>

<% if @beers %>
<%= paginate @beers %>
<%end%>

app/views/beers/edit.html.erb
<% if @beer.errors.any? %>
    <% @beer.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

<div class="page-header">
	<h1>Editing <em><%= @beer.nazwa %></em> <br/> <small><%= link_to 'or go back', beers_path %></small></h1>
</div>

<%= render 'form' %>

app/views/beers/foreign.html.erb
<div class="page-header">
  <h1>Beers</h1>
</div>

<ul class="nav nav-tabs nav-justified" role="tablist">
	<li><%= link_to raw("All <span class='label label-default'>"+@all_beers_count.to_s+'</span>'), beers_path %></li>
	<li><%= link_to raw("Polish <span class='label label-default'>"+@polish_beers_count.to_s+'</span>'), beers_polish_path %></li>
	<li class="active"><%= link_to raw("Foreign <span class='label label-default'>"+@foreign_beers_count.to_s+'</span>'), beers_foreign_path %></li>
</ul>

<div class="pull-left">
<br/>
<%= form_tag beers_foreign_path, :method => 'get', :class => "form-inline" do %>
  <%= select_tag(:shown, options_for_select([['Show all', "all"], ['Show ONLY bottles', "bottles"], ['Show everything EXCEPT bottles', "stickers"]], params[:shown]), :class => "form-control", :id => "shown") %>
<% end %>
</div>

<%= render 'list' %>

app/views/beers/index.html.erb
<div class="page-header">
  <h1>Beers</h1>
</div>

<ul class="nav nav-tabs nav-justified" role="tablist">
	<li class="active"><%= link_to raw("All <span class='label label-default'>"+@all_beers_count.to_s+'</span>'), beers_path %></li>
	<li><%= link_to raw("Polish <span class='label label-default'>"+@polish_beers_count.to_s+'</span>'), beers_polish_path %></li>
	<li><%= link_to raw("Foreign <span class='label label-default'>"+@foreign_beers_count.to_s+'</span>'), beers_foreign_path %></li>
</ul>

<div class="pull-left">
<br/>
<%= form_tag beers_path, :method => 'get', :class => "form-inline" do %>
  <%= select_tag(:shown, options_for_select([['Show all', "all"], ['Show ONLY bottles', "bottles"], ['Show everything EXCEPT bottles', "stickers"]], params[:shown]), :class => "form-control", :id => "shown") %>
<% end %>
</div>

<%= render 'list' %>

app/views/beers/new.html.erb
<% if @beer.errors.any? %>
    <% @beer.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>


<% if @new_beer %>
<div class="alert alert-success" role="alert"><strong>Success!</strong> <em><%= @new_beer.nazwa %></em> added as beer #<%= @new_beer.id %>!</div>
<% end %>

<% if @new_brewery %>
	<% unless @new_brewery.empty? %>
	<div class="alert alert-success" role="alert"><strong>Success!</strong> Brewery <em><%= @new_brewery %></em> added!</div>
	<% end %>
<% end %>

<div class="page-header">
	<h1>Add a new beer <small><%= link_to 'or go back', beers_path %></small></h1>
</div>

<%= render 'form' %>

app/views/beers/polish.html.erb
<div class="page-header">
  <h1>Beers</h1>
</div>

<ul class="nav nav-tabs nav-justified" role="tablist">
	<li><%= link_to raw("All <span class='label label-default'>"+@all_beers_count.to_s+'</span>'), beers_path %></li>
	<li class="active"><%= link_to raw("Polish <span class='label label-default'>"+@polish_beers_count.to_s+'</span>'), beers_polish_path %></li>
	<li><%= link_to raw("Foreign <span class='label label-default'>"+@foreign_beers_count.to_s+'</span>'), beers_foreign_path %></li>
</ul>

<div class="pull-left">
<br/>
<%= form_tag beers_polish_path, :method => 'get', :class => "form-inline" do %>
  <%= select_tag(:shown, options_for_select([['Show all', "all"], ['Show ONLY bottles', "bottles"], ['Show everything EXCEPT bottles', "stickers"]], params[:shown]), :class => "form-control", :id => "shown") %>
<% end %>
</div>

<%= render 'list' %>

app/views/beers/search.html.erb
<div class="page-header">
	<h1>Search<% if params[:term] %><% unless params[:term].empty? %>ing for "<em><%= params[:term] %></em>"
		 <small style="font-size: 40%"> get a <a href="/beers/search/<%= url_encode(params[:term]) %>">permalink</a> to this search</small>
		 <%end%></h1>
		<%end%>
</div>


<div style="max-width: 600px; margin: 0 auto">
	<%= form_tag beers_search_path, :method => 'get' do %>
	<div class="form-group">
		<div class="input-group">
			<%= text_field_tag :term, params[:term], :class => "form-control input-lg", :placeholder => "Beer name..."%>
				<div class="input-group-addon">
					<%= submit_tag "Search", :name => nil, :class => "btn btn-success", :style => "height: 32px" %>
				</div>
		</div>
	</div>
	<%end%>
</div>

<% if params[:term] %>
<% unless params[:term].empty? %>

<%= render 'searchlist' %>

<%end%>
<%end%>

app/views/beers/show.html.erb
<div class="media">

<div class="pull-right">
  <% if not @beer.local_image.url.nil? %>
  <%= link_to image_tag(@beer.local_image_url(:thumb), :class => "media-object beer-image"), @beer.local_image.url, :data => {:lightbox => "image"} %>
  <% elsif not @beer.foto.length < 1 %>
  <%= link_to image_tag(@beer.foto, :class => "media-object beer-image"), @beer.foto, :data => {:lightbox => "image"} %>
  <% else %>
	<img class="media-object beer-image" src="http://placehold.it/250x350&text=No+photo" />  
  <% end %>
</div>

<div class="page-header">
	<h1><%= @beer.nazwa %></h1>

	<h3 class="pull-right">
		<%= link_to "Edit", edit_beer_path(@beer), :class => "btn btn-primary" %>
		<%= link_to 'Delete', beer_path(@beer),
                    method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
	</h3>

</div>


<h2>Beer info:</h2>
<p>
  <strong>Brewery:</strong>
  <%= link_to @beer.brewery_name, brewery_path(Brewery.find(@beer.brewery_id)) %>
</p>
<p>
<strong>Country: </strong>
<% if @beer.country == "_" or @beer.country.empty? %>
  <img style="vertical-align: baseline" src="/assets/flags/_.png" /> <em>Unavailable</em>
<% else %>
  <img style="vertical-align: baseline" src="/assets/flags/<%= @beer.country %>.png" /> <%= IsoCountryCodes.find(@beer.country).name %> 
<%end>%>
</p>
<p>
<strong>Barcode: </strong> <em><%= @beer.barcode %></em>
<p>
  <strong>Comment:</strong> <%= raw(@beer.icons) %><br/>
  <% if @beer.komentarz.empty? %>
  	<em>Sorry! No comment found.</em>
  <% else %>
  <%= @beer.komentarz %>
  <% end %>
</p>
</div>