config/routes.rb
Beeronrails::Application.routes.draw do
  get "about/index"

  get "about", to: "about#index"
  
  get "beer/index"
  get "beer/denied"

  get "breweries/autocomplete"
  get "breweries/polish"
  get "breweries/foreign"
  get "breweries/search"
  get "breweries/search/:term", to: "breweries#search"

  get "beers/polish"
  get "beers/foreign"
  get "beers/new"
  get "beers/search"
  get "beers/search/:term", to: "beers#search"

  resources :beers
  resources :breweries

  root :to => "beers#index"

  match '*unmatched_route', :to => 'application#raise_not_found!'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <% if @beer %>
        <title><%= @beer.nazwa %> from <%= @beer.brewery_name %> - Beer On Rails</title>
    <% elsif @brewery %>
        <title><%= @brewery.nazwa %> - Beer On Rails</title>
    <% else %>
        <title>Beer On Rails</title>
    <%end%>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <meta name="author" content="Paweł J. Wal">
    <link rel="icon" type="image/gif" href="/assets/favicon.gif"/>
</head>


<body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img src="/assets/beericon.png" alt="" style="height: 84px"> Beer on Rails
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <% if logged_in? %>
                    <li>
                        <a><strong>You've got SuperCow powers!</strong></a>
                    </li>
                    <% end %>
                    <% if controller_name == "beers" %>
                        <%= form_tag beers_search_path, :method => 'get', :class => "navbar-form navbar-right" do %>
                        <div class="form-group">
                            <%= text_field_tag :term, params[:term], :class => "form-control", :placeholder => "Beer name..."%>
                        </div>
                        <%= submit_tag "Search", :name => nil, :class => "btn", :style => "height: 32px" %>
                        <%end%>
                    <%end%>
                    <% if controller_name == "breweries" %>
                        <%= form_tag breweries_search_path, :method => 'get', :class => "navbar-form navbar-right" do %>
                        <div class="form-group">
                            <%= text_field_tag :term, params[:term], :class => "form-control", :placeholder => "Brewery name..."%>
                        </div>
                        <%= submit_tag "Search", :name => nil, :class => "btn", :style => "height: 32px" %>
                        <%end%>
                    <%end%>
                    <li>
                        <%= link_to 'Add a beer', new_beer_path %>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Beers <span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "All", beers_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Polish", beers_polish_path %></li>
                        <li><%= link_to "Foreign", beers_foreign_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Search", beers_search_path %></li>
                      </ul>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Breweries <span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "All", breweries_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Polish", breweries_polish_path %></li>
                        <li><%= link_to "Foreign", breweries_foreign_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Search", breweries_search_path %></li>
                      </ul>
                    </li>
                    <li>
                        <%= link_to "About", about_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
    </nav>

    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <%= yield %>
            </div>
        </div>

        <hr/>

    <footer style="text-align: center">
        <p><a href="http://github.com/paweljw/beeronrails">Beer on Rails</a> was created by Paweł J. Wal</p>
        <p><small>deployed from <%= link_to @githeadid.to_s[0..9], "https://github.com/paweljw/beeronrails/commit/" + @githeadid %> - flags and other icons by <a href="http://famfamfam.com/lab/icons/">Mark James</a> - beer glass graphic by <a href="http://pixabay.com/en/icon-glass-cup-mug-beer-liquor-36869/">Nemo</a></small></p>
    </footer>

    </div>
    <!-- /.container -->
    <%= javascript_include_tag "application" %>
</body>
</html>